# Generated by Django 3.2 on 2021-05-10 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0003_hub_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubTargets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("q1", "Quarter 1"),
                            ("q2", "Quarter 2"),
                            ("q3", "Quarter 3"),
                            ("q4", "Quarter 4"),
                        ],
                        max_length=12,
                    ),
                ),
                ("instructions", models.PositiveIntegerField()),
                ("reductions", models.PositiveIntegerField()),
                ("new_business", models.PositiveIntegerField()),
                ("exchange_and_move", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Hub Target",
                "verbose_name_plural": "Hub Targets",
                "ordering": ["year", "quarter"],
            },
        ),
        migrations.AddField(
            model_name="hub",
            name="hub_targets",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_targets",
                to="regionandhub.hubtargets",
            ),
        ),
    ]
