# Generated by Django 3.2 on 2021-05-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0004_auto_20210510_1138"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hub",
            name="hub_targets",
        ),
        migrations.AddField(
            model_name="hubtargets",
            name="hub_targets",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_targets",
                to="regionandhub.hub",
            ),
        ),
    ]
