# Generated by Django 3.2 on 2021-05-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0005_auto_20210510_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubtargets",
            name="hub_targets",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_targets",
                to="regionandhub.hub",
            ),
        ),
    ]
