# Generated by Django 3.2 on 2021-05-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0008_alter_hub_region"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hubtargets",
            unique_together={("year", "quarter", "hub_targets")},
        ),
    ]
