# Generated by Django 3.2 on 2021-05-12 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0009_alter_hubtargets_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubTargetsYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                        ],
                        max_length=4,
                    ),
                ),
                ("targets_set", models.BooleanField(default=False)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_targets_set",
                        to="regionandhub.hub",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hub Target Set",
                "verbose_name_plural": "Hub Targets Set",
                "ordering": ["year", "hub"],
                "unique_together": {("year", "hub")},
            },
        ),
    ]
