# Generated by Django 3.2 on 2021-05-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0010_hubtargetsyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubtargetsyear",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_targets_year_set",
                to="regionandhub.hub",
            ),
        ),
    ]
