# Generated by Django 3.2.4 on 2021-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0011_alter_hubtargetsyear_hub"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubtargets",
            name="valuations",
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
