# Generated by Django 3.2 on 2021-05-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserTargetsByYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                        ],
                        max_length=4,
                    ),
                ),
                ("targets_set", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_targets_year_set",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Target Set",
                "verbose_name_plural": "User Targets Set",
                "ordering": ["user", "year"],
                "unique_together": {("year", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserTargets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("q1", "Quarter 1"),
                            ("q2", "Quarter 2"),
                            ("q3", "Quarter 3"),
                            ("q4", "Quarter 4"),
                        ],
                        max_length=12,
                    ),
                ),
                ("conveyancing", models.PositiveIntegerField()),
                ("mortgages", models.PositiveIntegerField()),
                ("instructions", models.PositiveIntegerField()),
                ("reductions", models.PositiveIntegerField()),
                ("new_business", models.PositiveIntegerField()),
                ("exchange_and_move", models.PositiveIntegerField()),
                (
                    "user_targets",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_targets",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Target",
                "verbose_name_plural": "User Targets",
                "ordering": ["year", "quarter"],
                "unique_together": {("year", "quarter", "user_targets")},
            },
        ),
    ]
