# Generated by Django 3.2 on 2021-05-13 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210513_1328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertargets",
            name="user_targets",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_targets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usertargetsbyyear",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_targets_year_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
