# Generated by Django 3.2 on 2021-05-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0005_auto_20210517_1334"),
        ("users", "0005_auto_20210513_1407"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertargets",
            name="user_invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_invitation_targets",
                to="invitations.userinvitations",
            ),
        ),
        migrations.AddField(
            model_name="usertargetsbyyear",
            name="user_invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_invitation_targets_year",
                to="invitations.userinvitations",
            ),
        ),
    ]
