# Generated by Django 3.2 on 2021-05-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210520_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email', 'is_active'], 'verbose_name': 'User & Profile', 'verbose_name_plural': 'Users & Profiles'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='o_comm',
            new_name='office_comm',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_comm',
            new_name='personal_comm',
        ),
    ]
