# Generated by Django 3.2 on 2021-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_profile_hub"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["user__email"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
