# Generated by Django 3.2.10 on 2022-01-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_featuretoggles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuretoggles',
            options={'ordering': ['user__email'], 'verbose_name': 'Feature Toggle', 'verbose_name_plural': 'Feature Toggles'},
        ),
        migrations.RemoveField(
            model_name='featuretoggles',
            name='profile',
        ),
        migrations.AddField(
            model_name='featuretoggles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_toggle', to='users.customuser'),
            preserve_default=False,
        ),
    ]
