# Generated by Django 3.2.10 on 2022-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220101_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggles',
            name='boards_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
