# Generated by Django 3.2.4 on 2021-08-10 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0086_alter_exchangemove_propertyprocess"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedProperties",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "lettings_service_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("intro_only", "Intro Only"),
                            ("rent_collect", "Rent Collect"),
                            ("fully_managed", "Fully Managed"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")]
                    ),
                ),
                (
                    "propertyprocess",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_properties",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Property",
                "verbose_name_plural": "Managed Properties",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                ],
            },
        ),
        migrations.CreateModel(
            name="Renewals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                ("renewed_on", models.DateField(null=True)),
                ("renewal_date", models.DateField()),
                (
                    "managed_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="lettings.managedproperties",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renewals",
                "verbose_name_plural": "Renewals",
                "ordering": [
                    "managed_property__propertyprocess__property__postcode",
                    "managed_property__propertyprocess__property__address_line_1",
                ],
            },
        ),
    ]
