# Generated by Django 3.2.4 on 2021-08-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managedproperties",
            name="is_active",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=True
            ),
        ),
    ]
