# Generated by Django 3.2.4 on 2021-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0012_remove_maintenance_next_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="priority",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Urgent"),
                    (2, "High"),
                    (3, "Medium"),
                    (4, "Low"),
                ],
                null=True,
            ),
        ),
    ]
