# Generated by Django 3.2.5 on 2021-12-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0002_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='landlord_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_property', to='touts.toutproperty'),
            preserve_default=False,
        ),
    ]
