# Generated by Django 3.2.5 on 2021-12-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_office_comm'),
        ('touts', '0003_landlord_landlord_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
