# Generated by Django 3.2.5 on 2021-12-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0004_landlord_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlord',
            options={'ordering': ['landlord_property__postcode', 'landlord_property__address_line_1', 'landlord_name'], 'verbose_name': 'Tout Landlord', 'verbose_name_plural': 'Tout Landlords'},
        ),
        migrations.AlterUniqueTogether(
            name='landlord',
            unique_together=set(),
        ),
    ]
