# Generated by Django 3.2.5 on 2021-12-01 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0005_auto_20211201_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToutLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='touts.landlord')),
            ],
            options={
                'verbose_name': 'Tout Letter',
                'verbose_name_plural': 'Tout Letters',
                'ordering': ['landlord__landlord_property__postcode', 'landlord__landlord_property__address_line_1', 'landlord__landlord_name'],
            },
        ),
    ]
