# Generated by Django 3.2.5 on 2021-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0006_toutletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='landlord_salutation',
            field=models.CharField(max_length=150),
            preserve_default=False,
        ),
    ]
