# Generated by Django 3.2.5 on 2021-12-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0009_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='toutproperty',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='touts.area'),
            preserve_default=False,
        ),
    ]
