# Generated by Django 3.2.5 on 2021-12-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0011_auto_20211205_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toutletter',
            name='landlord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='touts.landlord'),
        ),
    ]
