# Generated by Django 3.2.5 on 2021-12-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0012_alter_toutletter_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
