# Generated by Django 3.2.5 on 2021-12-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0013_area_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['area_code'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.RenameField(
            model_name='area',
            old_name='postcode',
            new_name='area_code',
        ),
    ]
