# Generated by Django 3.2.5 on 2021-12-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0014_auto_20211205_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
