# Generated by Django 3.2.5 on 2021-12-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0015_alter_area_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='toutproperty',
            name='county',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
