# Generated by Django 3.2.5 on 2021-12-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0016_toutproperty_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toutproperty',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
