# Generated by Django 3.2.5 on 2021-12-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0018_auto_20211213_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toutletter',
            options={'verbose_name': 'Tout Letter', 'verbose_name_plural': 'Tout Letters'},
        ),
        migrations.RemoveField(
            model_name='toutletter',
            name='landlord',
        ),
        migrations.AddField(
            model_name='toutletter',
            name='marketing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_info', to='touts.landlord'),
            preserve_default=False,
        ),
    ]
