# Generated by Django 3.2.5 on 2021-12-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0019_auto_20211213_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toutletter',
            options={'ordering': ['marketing__landlord'], 'verbose_name': 'Tout Letter', 'verbose_name_plural': 'Tout Letters'},
        ),
    ]
