# Generated by Django 3.2.5 on 2021-12-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0020_alter_toutletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toutletter',
            name='marketing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_info', to='touts.marketinginfo'),
        ),
    ]
