# Generated by Django 3.2.5 on 2021-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0021_alter_toutletter_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toutproperty',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
