# Generated by Django 3.2.10 on 2021-12-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0023_alter_landlord_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketinginfo',
            old_name='offer',
            new_name='price',
        ),
    ]
