# Generated by Django 3.2.5 on 2021-12-24 13:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0025_auto_20211222_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toutletter',
            name='do_not_send',
        ),
        migrations.RemoveField(
            model_name='toutletter',
            name='do_not_send_reason',
        ),
        migrations.RemoveField(
            model_name='toutletter',
            name='letter_five',
        ),
        migrations.RemoveField(
            model_name='toutletter',
            name='letter_four',
        ),
        migrations.RemoveField(
            model_name='toutletter',
            name='letter_one',
        ),
        migrations.RemoveField(
            model_name='toutletter',
            name='letter_six',
        ),
        migrations.RemoveField(
            model_name='toutletter',
            name='letter_three',
        ),
        migrations.RemoveField(
            model_name='toutletter',
            name='letter_two',
        ),
        migrations.AddField(
            model_name='marketinginfo',
            name='do_not_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketinginfo',
            name='do_not_send_reason',
            field=models.CharField(choices=[('laurels_success', 'Laurels Success'), ('off_the_market', 'Off The Market'), ('no_contact', 'Requested No Contact')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toutletter',
            name='letter',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toutletter',
            name='marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_info', to='touts.marketinginfo'),
        ),
    ]
