# Generated by Django 3.2.5 on 2021-12-24 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0026_auto_20211224_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='toutletter',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toutletter',
            name='letter',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
