# Generated by Django 3.2.5 on 2021-12-27 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0027_auto_20211224_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinginfo',
            name='furthest_letter',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
    ]
