# Generated by Django 3.2.5 on 2021-12-27 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0028_marketinginfo_furthest_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinginfo',
            name='furthest_letter',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
