# Generated by Django 3.2.5 on 2021-12-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0030_marketinginfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinginfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
