# Generated by Django 3.2.5 on 2021-12-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touts', '0031_alter_marketinginfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinginfo',
            name='do_not_send_reason',
            field=models.CharField(blank=True, choices=[('laurels_success', 'Laurels Success'), ('off_the_market', 'Off The Market'), ('no_contact', 'Requested No Contact')], max_length=50, null=True),
        ),
    ]
