# Generated by Django 3.2 on 2021-05-18 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                ("address_line_1", models.CharField(max_length=150)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("town", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=8)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            (
                                "House",
                                (
                                    ("house_terraced", "House - Terraced"),
                                    (
                                        "house_end_terrace",
                                        "House - End of Terrace",
                                    ),
                                    (
                                        "house_semi_detached",
                                        "House - Semi-Detached",
                                    ),
                                    ("house_detached", "House - Detached"),
                                ),
                            ),
                            (
                                "Flat",
                                (
                                    (
                                        "maisonette_ground_floor",
                                        "Maisonette - Ground Floor",
                                    ),
                                    (
                                        "maisonette_top_floor",
                                        "Maisonette - Top Floor",
                                    ),
                                    (
                                        "flat_ground_floor",
                                        "Flat - Ground Floor",
                                    ),
                                    (
                                        "flat_upper_floor",
                                        "Flat - Upper Floors",
                                    ),
                                ),
                            ),
                            (
                                "Bungalow",
                                (
                                    (
                                        "bungalow_semi_detached",
                                        "Bungalow - Semi-Detached",
                                    ),
                                    (
                                        "bungalow_detached",
                                        "Bungalow - Detached",
                                    ),
                                ),
                            ),
                            (
                                "Other",
                                (
                                    ("commercial", "Commercial"),
                                    ("land", "Land"),
                                    ("other", "Other"),
                                ),
                            ),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "property_style",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("new_build", "New Build"),
                            ("period", "Period"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "number_of_bedrooms",
                    models.CharField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tenure",
                    models.CharField(
                        choices=[
                            ("freehold", "Freehold"),
                            ("leasehold", "Leasehold"),
                            ("share_of_freehold", "Share of Freehold"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "floor_space",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["postcode", "address_line_1"],
                "unique_together": {
                    ("postcode", "address_line_1", "address_line_2")
                },
            },
        ),
    ]
