# Generated by Django 3.2 on 2021-05-21 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_valuation"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructionLettingsExtra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "lettings_service_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("intro_only", "Intro Only"),
                            ("rent_collect", "Rent Collect"),
                            ("fully_managed", "Fully Managed"),
                            (
                                "fully_managed_ri",
                                "Fully Managed Rent Insurance Included",
                            ),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "managed_property",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "propertyprocess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruction_letting_extra",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction Lettings Extra",
                "verbose_name_plural": "Instructions Lettings Extra",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                ],
            },
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[("sole", "Sole"), ("multi", "Multi")],
                        max_length=15,
                    ),
                ),
                ("listing_price", models.IntegerField()),
                (
                    "fee_agreed",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "length_of_contract",
                    models.IntegerField(
                        choices=[
                            (16, "16 Weeks"),
                            (12, "12 Weeks"),
                            (10, "10 Weeks"),
                            (8, "8 Weeks"),
                            (6, "6 Weeks"),
                            (4, "4 Weeks (Multi Only)"),
                        ]
                    ),
                ),
                (
                    "marketing_board",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")]
                    ),
                ),
                (
                    "propertyprocess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruction",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction",
                "verbose_name_plural": "Instructions",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                ],
            },
        ),
    ]
