# Generated by Django 3.2 on 2021-05-21 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_auto_20210521_1317"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("other", "Other")], max_length=40
                    ),
                ),
                ("description", models.CharField(max_length=400)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "propertyprocess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property History",
                "verbose_name_plural": "Property History",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                    "created",
                ],
            },
        ),
    ]
