# Generated by Django 3.2 on 2021-05-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_profile_hub"),
        ("properties", "0008_auto_20210525_1215"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyhistory",
            options={
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                    "-created",
                ],
                "verbose_name": "Property History",
                "verbose_name_plural": "Property History",
            },
        ),
        migrations.AddField(
            model_name="valuation",
            name="valuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.profile"
            ),
            preserve_default=False,
        ),
    ]
