# Generated by Django 3.2 on 2021-05-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_offererdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offererdetails",
            name="completed_offer_form",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
