# Generated by Django 3.2 on 2021-05-26 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_offererdetails_completed_offer_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffererMortgage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verified', models.BooleanField(default=False, null=True)),
                ('verified_status', models.CharField(choices=[('pending', 'Pending'), ('verified_mr', 'Verified By Mortgage Required'), ('mip', 'Mortgage In Principle Seen'), ('unable', 'Unable To Verify')], max_length=50)),
                ('offerer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerer_mortgage_details', to='properties.offererdetails')),
                ('propertyprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerer_mortgage_details', to='properties.propertyprocess')),
            ],
            options={
                'verbose_name': 'Offerer Mortgage Details',
                'verbose_name_plural': 'Offerer Mortgage Details',
                'ordering': ['propertyprocess__property__postcode', 'propertyprocess__property__address_line_1', 'offerer_details__full_name'],
            },
        ),
    ]
