# Generated by Django 3.2 on 2021-05-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_offerermortgage_offerer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerermortgage',
            name='offerer_details',
        ),
    ]
