# Generated by Django 3.2 on 2021-05-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_offerermortgage_offerer_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerermortgage',
            options={'ordering': ['offerer_details__propertyprocess__property__postcode', 'offerer_details__propertyprocess__property__address_line_1', 'offerer_details__full_name'], 'verbose_name': 'Offerer Mortgage Details', 'verbose_name_plural': 'Offerer Mortgage Details'},
        ),
        migrations.RemoveField(
            model_name='offerermortgage',
            name='propertyprocess',
        ),
    ]
