# Generated by Django 3.2 on 2021-05-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0021_remove_offerermortgage_propertyprocess"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerermortgage",
            name="propertyprocess",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.propertyprocess",
            ),
            preserve_default=False,
        ),
    ]
