# Generated by Django 3.2 on 2021-05-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0022_offerermortgage_propertyprocess"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offerermortgage",
            name="propertyprocess",
        ),
    ]
