# Generated by Django 3.2 on 2021-05-27 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0023_remove_offerermortgage_propertyprocess"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffererCash",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "cash",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("sale_of_property", "Sale of Property"),
                            ("gift", "Gift"),
                            ("re_mortgage", "Re-Mortgage"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "offerer_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerer_cash_details",
                        to="properties.offererdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offerer Cash Details",
                "verbose_name_plural": "Offerer Cash Details",
                "ordering": [
                    "offerer_details__propertyprocess__property__postcode",
                    "offerer_details__propertyprocess__property__address_line_1",
                    "offerer_details__full_name",
                ],
            },
        ),
    ]
