# Generated by Django 3.2 on 2021-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyprocess',
            name='legacy_property',
            field=models.BooleanField(choices=[(True, 'Legacy'), (False, 'Not Legacy')], default=False),
        ),
    ]
