# Generated by Django 3.2 on 2021-06-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='propertyprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='properties.propertyprocess'),
            preserve_default=False,
        ),
    ]
