# Generated by Django 3.2 on 2021-06-01 16:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_alter_deal_propertyprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='offer_accepted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_accepted', to='properties.offer'),
        ),
        migrations.CreateModel(
            name='ExchangeMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('exchange_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('propertyprocess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_and_move', to='properties.propertyprocess')),
            ],
            options={
                'verbose_name': 'Exchange & Move',
                'verbose_name_plural': 'Exchange & Move',
                'ordering': ['propertyprocess__property__postcode', 'propertyprocess__property__address_line_1'],
            },
        ),
    ]
