# Generated by Django 3.2 on 2021-06-01 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0031_auto_20210601_1724"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "laurels_aml_checks",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "laurels_aml_checks_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "buyers_initial_solicitors_paperwork",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "buyers_initial_solicitors_paperwork_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "sellers_inital_solicitors_paperwork",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "sellers_inital_solicitors_paperwork_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "draft_contracts_recieved_by_buyers_solicitors",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "draft_contracts_recieved_by_buyers_solicitors_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "searches_paid_for",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "searches_paid_for_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "searches_ordered",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "searches_ordered_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "mortgage_application_submitted",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "mortgage_application_submitted_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "mortgage_survey_arranged",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "mortgage_survey_arranged_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "mortgage_survey_completed",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "mortgage_survey_completed_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "all_search_results_recieved",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "all_search_results_recieved_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "enquiries_raised",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "enquiries_raised_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "structural_survey_booked",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "structural_survey_booked_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "structural_survey_completed",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "structural_survey_completed_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "enquiries_answered",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "enquiries_answered_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "additional_enquiries_raised",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "additional_enquiries_raised_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "all_enquiries_answered",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "all_enquiries_answered_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "final_contracts_sent_out",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "final_contracts_sent_out_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "buyers_final_contracts_signed",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "buyers_final_contracts_signed_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "sellers_final_contracts_signed",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "sellers_final_contracts_signed_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "buyers_deposit_sent",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "buyers_deposit_sent_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "buyers_deposit_recieved",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "buyers_deposit_recieved_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "completion_date_agreed",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "completion_date_agreed_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "sales_notes",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "propertyprocess",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_status",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Status",
                "verbose_name_plural": "Sale Status'",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleStatusSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "show_mortgage",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Show"), (False, "Hide")],
                        default=True,
                        null=True,
                    ),
                ),
                (
                    "show_survey",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Show"), (False, "Hide")],
                        default=True,
                        null=True,
                    ),
                ),
                (
                    "sale_status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_status_settings",
                        to="properties.salestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Status Settings",
                "verbose_name_plural": "Sale Status' Settings",
                "ordering": [
                    "sale_status__propertyprocess__property__postcode",
                    "sale_status__propertyprocess__property__address_line_1",
                ],
            },
        ),
    ]
