# Generated by Django 3.2 on 2021-06-02 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0032_salestatus_salestatussettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleStatusPhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                ("phase_1", models.BooleanField(default=False)),
                ("phase_2", models.BooleanField(default=False)),
                ("phase_3", models.BooleanField(default=False)),
                ("phase_4", models.BooleanField(default=False)),
                (
                    "sale_status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_status_phase",
                        to="properties.salestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Status Phase",
                "verbose_name_plural": "Sale Status' Phase",
                "ordering": [
                    "sale_status__propertyprocess__property__postcode",
                    "sale_status__propertyprocess__property__address_line_1",
                ],
            },
        ),
    ]
