# Generated by Django 3.2 on 2021-06-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0034_salestatusphase_overall_phase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salestatus",
            old_name="laurels_aml_checks",
            new_name="buyers_aml_checks_and_sales_memo",
        ),
        migrations.RenameField(
            model_name="salestatus",
            old_name="laurels_aml_checks_date",
            new_name="buyers_aml_checks_and_sales_memo_date",
        ),
    ]
