# Generated by Django 3.2 on 2021-06-04 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0043_alter_marketing_contact_laurels"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyFees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
                ("deal_date", models.DateField(blank=True, null=True)),
                ("new_business", models.FloatField(blank=True, null=True)),
                ("deal", models.BooleanField(default=False, null=True)),
                ("show_all", models.BooleanField(default=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "propertyprocess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_fees",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Fee",
                "verbose_name_plural": "Property Fees",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                ],
            },
        ),
    ]
