# Generated by Django 3.2 on 2021-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_propertyfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyfees',
            name='deal',
        ),
        migrations.AlterField(
            model_name='propertyfees',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
