# Generated by Django 3.2 on 2021-06-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_auto_20210607_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyfees',
            options={'ordering': ['propertyprocess__property__postcode', 'propertyprocess__property__address_line_1', 'date'], 'verbose_name': 'Property Fee', 'verbose_name_plural': 'Property Fees'},
        ),
        migrations.RenameField(
            model_name='propertyfees',
            old_name='deal_date',
            new_name='date',
        ),
    ]
