# Generated by Django 3.2 on 2021-06-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0049_alter_property_number_of_bedrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=150),
            preserve_default=False,
        ),
    ]
