# Generated by Django 3.2 on 2021-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0052_alter_propertyprocess_macro_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructionlettingsextra",
            name="lettings_service_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("intro_only", "Intro Only"),
                    ("rent_collect", "Rent Collect"),
                    ("fully_managed", "Fully Managed"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
