# Generated by Django 3.2 on 2021-06-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0054_reductions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reductions",
        ),
    ]
