# Generated by Django 3.2 on 2021-06-16 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0057_alter_propertyfees_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressionNotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "propertyprocess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression_notes",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression Note",
                "verbose_name_plural": "Progression Notes",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                    "-created",
                ],
            },
        ),
    ]
