# Generated by Django 3.2 on 2021-06-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0058_progressionnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesprogression',
            name='sales_notes',
        ),
    ]
