# Generated by Django 3.2 on 2021-06-16 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0059_remove_salesprogression_sales_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertySellingInformation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                ("seller_name", models.CharField(max_length=100, null=True)),
                ("seller_phone", models.IntegerField(null=True)),
                ("seller_email", models.EmailField(max_length=100, null=True)),
                ("buyer_name", models.CharField(max_length=100, null=True)),
                ("buyer_phone", models.IntegerField(null=True)),
                ("buyer_email", models.EmailField(max_length=100, null=True)),
                (
                    "seller_sol_name",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "seller_sol_firm",
                    models.CharField(max_length=100, null=True),
                ),
                ("seller_sol_phone", models.IntegerField(null=True)),
                (
                    "seller_sol_email",
                    models.EmailField(max_length=100, null=True),
                ),
                (
                    "buyer_sol_firm",
                    models.CharField(max_length=100, null=True),
                ),
                ("buyer_sol_phone", models.IntegerField(null=True)),
                (
                    "buyer_sol_name",
                    models.EmailField(max_length=100, null=True),
                ),
                ("broker_firm", models.CharField(max_length=100, null=True)),
                ("broker_phone", models.IntegerField(null=True)),
                ("broker_name", models.EmailField(max_length=100, null=True)),
                (
                    "propertyprocess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selling_information",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Selling Information",
                "verbose_name_plural": "Selling Information",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                ],
            },
        ),
    ]
