# Generated by Django 3.2 on 2021-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0061_alter_propertysellinginformation_propertyprocess",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertysellinginformation",
            name="buyer_sol_email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="buyer_sol_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
