# Generated by Django 3.2 on 2021-06-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0062_auto_20210616_1700"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertysellinginformation",
            name="broker_email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="broker_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
