# Generated by Django 3.2 on 2021-06-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0063_auto_20210616_1705"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": [
                    "offerer_details__propertyprocess__property__postcode",
                    "offerer_details__propertyprocess__property__address_line_1",
                    "offerer_details__full_name",
                    "-date",
                    "-created",
                ],
                "verbose_name": "Offer Details",
                "verbose_name_plural": "Offer Details",
            },
        ),
        migrations.AlterModelOptions(
            name="propertyfees",
            options={
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                    "-date",
                    "-created",
                ],
                "verbose_name": "Property Fee",
                "verbose_name_plural": "Property Fees",
            },
        ),
    ]
