# Generated by Django 3.2 on 2021-06-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0064_auto_20210618_1530"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offererdetails",
            name="email",
        ),
    ]
