# Generated by Django 3.2.4 on 2021-06-28 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0066_offererdetails_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructionChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("sole_to_multi", "Sole To Multi"),
                            ("multi_to_sole", "Multi To Sole"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "fee_agreed",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "length_of_contract",
                    models.IntegerField(
                        choices=[
                            (16, "16 Weeks"),
                            (12, "12 Weeks"),
                            (10, "10 Weeks"),
                            (8, "8 Weeks"),
                            (6, "6 Weeks"),
                            (4, "4 Weeks (Multi Only)"),
                        ]
                    ),
                ),
                (
                    "propertyprocess",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruction_change",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction Change",
                "verbose_name_plural": "Instruction Changes",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                ],
            },
        ),
    ]
