# Generated by Django 3.2.4 on 2021-06-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0067_instructionchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructionchange",
            name="agreement_type_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructionchange",
            name="fee_agreed_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructionchange",
            name="length_of_contract_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="instructionchange",
            name="fee_agreed",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="instructionchange",
            name="length_of_contract",
            field=models.IntegerField(
                choices=[
                    (16, "16 Weeks"),
                    (12, "12 Weeks"),
                    (10, "10 Weeks"),
                    (8, "8 Weeks"),
                    (6, "6 Weeks"),
                    (4, "4 Weeks (Multi Only)"),
                ],
                null=True,
            ),
        ),
    ]
