# Generated by Django 3.2.4 on 2021-06-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0068_auto_20210628_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructionchange",
            name="agreement_type",
            field=models.CharField(
                choices=[("multi", "Multi"), ("sole", "Sole")], max_length=15
            ),
        ),
    ]
