# Generated by Django 3.2.4 on 2021-07-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0070_dealchange"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DealChange",
        ),
    ]
