# Generated by Django 3.2.4 on 2021-07-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0071_delete_dealchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesprogression',
            old_name='mortgage_survey_completed',
            new_name='mortgage_offer_with_solicitors',
        ),
        migrations.RenameField(
            model_name='salesprogression',
            old_name='mortgage_survey_completed_date',
            new_name='mortgage_offer_with_solicitors_date',
        ),
    ]
