# Generated by Django 3.2.4 on 2021-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0072_auto_20210706_1206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="broker_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="broker_firm",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="broker_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="broker_phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="buyer_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="buyer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="buyer_phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="buyer_sol_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="buyer_sol_firm",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="buyer_sol_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="buyer_sol_phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="seller_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="seller_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="seller_phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="seller_sol_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="seller_sol_firm",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="seller_sol_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="propertysellinginformation",
            name="seller_sol_phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
