# Generated by Django 3.2.4 on 2021-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0074_alter_propertychain_chain_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyprocess',
            name='previously_fallen_through',
            field=models.BooleanField(default=False),
        ),
    ]
