# Generated by Django 3.2.4 on 2021-07-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0075_propertyprocess_previously_fallen_through"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertychain",
            options={
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                    "order",
                ],
                "verbose_name": "Sales Progression Chain",
                "verbose_name_plural": "Sales Progressions Chain",
            },
        ),
        migrations.RemoveField(
            model_name="propertychain",
            name="sales_progression",
        ),
        migrations.AddField(
            model_name="propertychain",
            name="propertyprocess",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_chain",
                to="properties.propertyprocess",
            ),
            preserve_default=False,
        ),
    ]
