# Generated by Django 3.2.4 on 2021-08-04 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0078_auto_20210715_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffererDetailsLettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('completed_offer_form', models.BooleanField(choices=[(True, 'Completed'), (False, 'Incomplete')], default=False, null=True)),
                ('propertyprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerer_details_lettings', to='properties.propertyprocess')),
            ],
            options={
                'verbose_name': 'Offerer History Lettings',
                'verbose_name_plural': 'Offerer History Lettings',
                'ordering': ['propertyprocess__property__postcode', 'propertyprocess__property__address_line_1', 'full_name'],
            },
        ),
    ]
