# Generated by Django 3.2.4 on 2021-08-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0081_auto_20210804_1321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerlettingsextra",
            name="proposed_move_in_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="offerlettingsextra",
            name="term",
            field=models.IntegerField(
                choices=[
                    (6, "6 Months"),
                    (12, "12 Months"),
                    (18, "18 Months"),
                    (24, "24 Months"),
                ],
                null=True,
            ),
        ),
    ]
