# Generated by Django 3.2.4 on 2021-08-04 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0082_auto_20210804_1427"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealExtraLettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "term",
                    models.IntegerField(
                        choices=[
                            (6, "6 Months"),
                            (12, "12 Months"),
                            (18, "18 Months"),
                            (24, "24 Months"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "break_clause",
                    models.IntegerField(
                        choices=[
                            (0, "No Break Clause"),
                            (6, "6 Months"),
                            (12, "12 Months"),
                            (18, "18 Months"),
                            (24, "24 Months"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_extra",
                        to="properties.deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal Extra",
                "verbose_name_plural": "Deal Extra",
                "ordering": [
                    "deal__propertyprocess__property__postcode",
                    "deal__propertyprocess__property__address_line_1",
                    "deal__date",
                ],
            },
        ),
    ]
