# Generated by Django 3.2.4 on 2021-08-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0085_exchangemovelettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemove',
            name='propertyprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_and_move', to='properties.propertyprocess'),
        ),
    ]
