# Generated by Django 3.2.4 on 2021-08-11 09:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0086_alter_exchangemove_propertyprocess"),
    ]

    operations = [
        migrations.CreateModel(
            name="LettingsProgression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "contact_touch_point_to_ll_and_tt",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "contact_touch_point_to_ll_and_tt_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "reference_forms_sent_to_tenant",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "reference_forms_sent_to_tenant_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "compliance_form_sent_to_landlord",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "compliance_form_sent_to_landlord_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "google_drive_and_email_inbox",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "google_drive_and_email_inbox_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "tenancy_created_on_expert_agent",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "tenancy_created_on_expert_agent_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "references_passed",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "references_passed_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "gas_safety_certificate",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "gas_safety_certificate_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "electrical_certificate",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "electrical_certificate_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "epc_certificate",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "epc_certificate_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "tenancy_certificate_sent",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "tenancy_certificate_sent_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "tenancy_certificate_signed",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "tenancy_certificate_signed_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "tenant_invoice_sent",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "tenant_invoice_sent_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "move_in_funds_received",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "move_in_funds_received_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "prescribed_info_and_statutory_docs_sent",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "prescribed_info_and_statutory_docs_sent_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "deposit_registered_with_tds",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "deposit_registered_with_tds_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "landlord_invoices_sent_to_ea",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "landlord_invoices_sent_to_ea_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "right_to_rent",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Done"), (False, "Not Done")],
                        default=False,
                        null=True,
                    ),
                ),
                (
                    "right_to_rent_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "propertyprocess",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lettings_progression",
                        to="properties.propertyprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettings Progression",
                "verbose_name_plural": "Lettings Progressions",
                "ordering": [
                    "propertyprocess__property__postcode",
                    "propertyprocess__property__address_line_1",
                ],
            },
        ),
        migrations.CreateModel(
            name="LettingsProgressionSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "show_gas",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Show"), (False, "Hide")],
                        default=True,
                        null=True,
                    ),
                ),
                (
                    "lettings_progression",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lettings_progression_settings",
                        to="properties.lettingsprogression",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettings Progression Settings",
                "verbose_name_plural": "Lettings Progressions Settings",
                "ordering": [
                    "lettings_progression__propertyprocess__property__postcode",
                    "lettings_progression__propertyprocess__property__address_line_1",
                ],
            },
        ),
        migrations.CreateModel(
            name="LettingsProgressionPhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "overall_phase",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Phase 1 Complete"),
                            (2, "Phase 2 Complete"),
                            (3, "Phase 3 Complete"),
                            (4, "Phase 4 Complete"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("phase_1", models.BooleanField(default=False)),
                ("phase_2", models.BooleanField(default=False)),
                ("phase_3", models.BooleanField(default=False)),
                ("phase_4", models.BooleanField(default=False)),
                (
                    "lettings_progression",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lettings_progression_phase",
                        to="properties.lettingsprogression",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettings Progression Phase",
                "verbose_name_plural": "Lettings Progressions Phase",
                "ordering": [
                    "lettings_progression__propertyprocess__property__postcode",
                    "lettings_progression__propertyprocess__property__address_line_1",
                ],
            },
        ),
    ]
