# Generated by Django 3.2.4 on 2021-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0090_alter_dealextralettings_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offererdetails',
            name='completed_offer_form',
            field=models.BooleanField(blank=True, choices=[(True, 'Completed'), (False, 'Incomplete')], default=False, null=True),
        ),
    ]
