# Generated by Django 3.2.4 on 2021-08-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0091_alter_offererdetails_completed_offer_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offererdetails',
            name='completed_offer_form',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
