# Generated by Django 3.2.4 on 2021-08-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0093_auto_20210816_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuation",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="propertyprocess",
            name="furthest_status",
            field=models.IntegerField(
                choices=[
                    (-1, "Archived"),
                    (0, "Withdrawn"),
                    (1, "Awaiting Valuation"),
                    (2, "Valuation Complete"),
                    (3, "Instructed - On The Market"),
                    (4, "Deal"),
                    (5, "Complete"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="propertyprocess",
            name="macro_status",
            field=models.IntegerField(
                choices=[
                    (-1, "Archived"),
                    (0, "Withdrawn"),
                    (1, "Awaiting Valuation"),
                    (2, "Valuation Complete"),
                    (3, "Instructed - On The Market"),
                    (4, "Deal"),
                    (5, "Complete"),
                ]
            ),
        ),
    ]
