# Generated by Django 3.2.4 on 2021-09-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_profile_office_comm"),
        ("properties", "0095_instruction_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="lettingsprogression",
            name="primary_progressor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lettings_progressor",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="salesprogression",
            name="primary_progressor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_progressor",
                to="users.profile",
            ),
        ),
    ]
