# Generated by Django 3.2.5 on 2021-11-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0097_lettingslandlordorlaurelsinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='waiting_on_chain',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
