# Generated by Django 3.2.10 on 2022-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0098_offer_waiting_on_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyprocess',
            name='boards',
            field=models.BooleanField(default=False),
        ),
    ]
