# Generated by Django 3.2.11 on 2022-02-07 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0099_propertyfeemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfeemaster',
            name='propertyprocess',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_fees_master', to='properties.propertyprocess'),
        ),
    ]
