# Generated by Django 3.2.12 on 2022-02-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0100_alter_propertyfeemaster_propertyprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfees',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
