# Generated by Django 3.2.15 on 2022-08-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0101_propertyfees_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='why_did_they_instruct_us',
            field=models.CharField(blank=True, choices=[('fees', 'Fees'), ('consultant', 'Consultant'), ('recommendation', 'Recommendation'), ('marketing', 'Marketing'), ('area_success', 'Area Success'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='hear_about_laurels',
            field=models.CharField(choices=[('previous_client', 'Previous Client'), ('applicant', 'Applicant'), ('social_media', 'Social Media Posts'), ('recommendation', 'Recommendation'), ('door_knocking', 'Door Knocking'), ('print_drop', 'Print Drop'), ('web_search', 'Web Search'), ('boards', 'Boards'), ('laurels_team_member_friends_or_family_of_laurels', 'Laurels Team Member/Friends or Family of Laurels'), ('local_presence', 'Local Presence'), ('sold_on_road', 'Sold on Road')], max_length=100, null=True),
        ),
    ]
