# Generated by Django 3.2.15 on 2022-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0102_auto_20220829_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
