# Generated by Django 3.2.15 on 2022-08-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0103_marketing_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='contact_laurels',
            field=models.CharField(choices=[('phone_call_to_office', 'Direct Call'), ('direct_email', 'Direct Email'), ('website_message', 'Website Enquiry'), ('social_media_message', 'Social Media'), ('laurels_pro-actively_asked', 'Laurels Contacted Them')], max_length=100, null=True),
        ),
    ]
