# Generated by Django 3.2.4 on 2021-09-03 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeekendDays",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Weekend Day",
                "verbose_name_plural": "Weekend Days",
                "ordering": [],
            },
        ),
    ]
