# Generated by Django 3.2.4 on 2021-09-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0012_hubtargets_valuations"),
        ("weekends", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weekenddays",
            options={
                "ordering": ["start"],
                "verbose_name": "Weekend Day",
                "verbose_name_plural": "Weekend Days",
            },
        ),
        migrations.AddField(
            model_name="weekenddays",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekend_hub",
                to="regionandhub.hub",
            ),
            preserve_default=False,
        ),
    ]
