# Generated by Django 3.2.4 on 2021-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekends", "0002_auto_20210905_1819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weekenddays",
            name="end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="weekenddays",
            name="start",
            field=models.DateField(),
        ),
    ]
