# Generated by Django 3.2.13 on 2022-06-02 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_remove_profile_office_comm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastQuarterLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('valuations', 'Valuations'), ('instructions', 'Instructions'), ('reductions', 'Reductions'), ('new_business', 'New Business')], max_length=40)),
                ('count', models.IntegerField()),
                ('target_percentage', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboard',
                'ordering': ['type', 'count'],
            },
        ),
    ]
