# Generated by Django 3.2.13 on 2022-06-02 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIsChanged',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('valuations', 'Valuations'), ('instructions', 'Instructions'), ('reductions', 'Reductions'), ('new_business', 'New Business'), ('leaderboard', 'Leaderboard')], max_length=40)),
                ('is_changed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Leaderboard Data Changed',
                'verbose_name_plural': 'Leaderboard Data Changed',
            },
        ),
        migrations.AlterModelOptions(
            name='lastquarterleaderboard',
            options={'ordering': ['type', '-count'], 'verbose_name': 'Leaderboard', 'verbose_name_plural': 'Leaderboard'},
        ),
    ]
