# Generated by Django 3.2 on 2021-05-13 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regionandhub", "0011_alter_hubtargetsyear_hub"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("invited", models.DateTimeField(auto_now_add=True)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "director",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hub",
                    models.ManyToManyField(
                        blank=True, null=True, to="regionandhub.Hub"
                    ),
                ),
                (
                    "hub_targets",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_hub_targets",
                        to="regionandhub.hubtargets",
                    ),
                ),
                (
                    "hub_targets_year",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_hub_targets_year",
                        to="regionandhub.hubtargetsyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Invitation",
                "verbose_name_plural": "User Invitations",
                "ordering": ["invited"],
            },
        ),
    ]
