# Generated by Django 3.2 on 2021-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regionandhub", "0011_alter_hubtargetsyear_hub"),
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitations",
            name="hub",
            field=models.ManyToManyField(to="regionandhub.Hub"),
        ),
    ]
