# Generated by Django 3.2 on 2021-05-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0002_alter_userinvitations_hub"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvitations",
            name="employee_targets",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinvitations",
            name="is_staff",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
