# Generated by Django 3.2 on 2021-05-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0003_auto_20210513_1418"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitations",
            name="is_staff",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
