# Generated by Django 3.2 on 2021-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0007_alter_userinvitations_invited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitations",
            name="invited",
            field=models.DateTimeField(null=True),
        ),
    ]
