# Generated by Django 3.2.10 on 2022-01-01 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0099_propertyprocess_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('propertyref', models.IntegerField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('propertyprocess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='properties.propertyprocess')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': [],
            },
        ),
    ]
