# Generated by Django 3.2.10 on 2022-01-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='propertyref',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
