# Generated by Django 3.2.10 on 2022-01-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_boards_propertyref'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='created_on_signmaster',
            field=models.BooleanField(default=False),
        ),
    ]
