# Generated by Django 3.2.10 on 2022-01-03 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_boards_signmaster_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'ordering': ['propertyprocess__property__postcode', 'propertyprocess__property__address_line_1', '-created'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.CreateModel(
            name='BoardsInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('boards', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_info', to='boards.boards')),
            ],
            options={
                'verbose_name': 'Board Info',
                'verbose_name_plural': 'Boards Info',
                'ordering': [],
            },
        ),
    ]
