# Generated by Django 3.2.10 on 2022-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20220103_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardsinfo',
            name='address1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='boardsinfo',
            name='address2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='boardsinfo',
            name='agentnotes',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='boardsinfo',
            name='boardstatusid',
            field=models.IntegerField(choices=[(1, 'For Sale'), (2, 'To Let'), (3, 'Sold'), (4, 'Let By'), (5, 'Sale Agreed'), (6, 'Under Offer'), (7, 'Let & Managed By')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardsinfo',
            name='county',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='boardsinfo',
            name='houseno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='boardsinfo',
            name='postcode',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='boardsinfo',
            name='town',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='boardsinfo',
            name='vendor_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
