# Generated by Django 3.2.10 on 2022-01-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20220103_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsinfo',
            name='boardstatusid',
            field=models.IntegerField(blank=True, choices=[(1, 'For Sale'), (2, 'To Let'), (3, 'Sold'), (4, 'Let By'), (5, 'Sale Agreed'), (6, 'Under Offer'), (7, 'Let & Managed By')], null=True),
        ),
    ]
