# Generated by Django 3.2.10 on 2022-01-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_alter_boardsinfo_boardstatusid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsinfo',
            options={'verbose_name': 'Board Info', 'verbose_name_plural': 'Boards Info'},
        ),
    ]
