# Generated by Django 3.2.10 on 2022-01-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_alter_boardsinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardsinfo',
            name='activate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
